create table bitly_demo_link
(
    id int generated by default as identity,
    hash_value varchar(50) not null,
    original_url varchar(2048) not null,
    username varchar(100) not null,
    ver int not null,
    primary key(id),
    unique(hash_value, ver)
);